# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sentenceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(545, 341)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMouseTracking(False)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setAcceptDrops(False)
        self.infoTable = QtWidgets.QTableWidget(Form)
        self.infoTable.setGeometry(QtCore.QRect(10, 120, 511, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoTable.sizePolicy().hasHeightForWidth())
        self.infoTable.setSizePolicy(sizePolicy)
        self.infoTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.infoTable.setRowCount(5)
        self.infoTable.setColumnCount(5)
        self.infoTable.setObjectName("infoTable")
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setItem(0, 3, item)
        self.embeddingCbBox = QtWidgets.QComboBox(Form)
        self.embeddingCbBox.setGeometry(QtCore.QRect(100, 40, 87, 22))
        self.embeddingCbBox.setObjectName("embeddingCbBox")
        self.embeddingLabel = QtWidgets.QLabel(Form)
        self.embeddingLabel.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.embeddingLabel.setObjectName("embeddingLabel")
        self.queryBtn = QtWidgets.QPushButton(Form)
        self.queryBtn.setGeometry(QtCore.QRect(230, 40, 93, 28))
        self.queryBtn.setObjectName("queryBtn")
        self.addItemBtn = QtWidgets.QPushButton(Form)
        self.addItemBtn.setGeometry(QtCore.QRect(350, 40, 93, 28))
        self.addItemBtn.setObjectName("addItemBtn")
        self.addRowBtn = QtWidgets.QPushButton(Form)
        self.addRowBtn.setGeometry(QtCore.QRect(450, 40, 93, 28))
        self.addRowBtn.setObjectName("addRowBtn")
        self.delRowBtn = QtWidgets.QPushButton(Form)
        self.delRowBtn.setGeometry(QtCore.QRect(550, 40, 93, 28))
        self.delRowBtn.setObjectName("delRowBtn")


        self.adviceLabel = QtWidgets.QLabel(Form)
        self.adviceLabel.setGeometry(QtCore.QRect(20, 80, 501, 16))
        self.adviceLabel.setObjectName("adviceLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SentenceManger"))
        __sortingEnabled = self.infoTable.isSortingEnabled()
        self.infoTable.setSortingEnabled(False)
        self.setTableTitle()
        self.infoTable.setSortingEnabled(__sortingEnabled)
        self.embeddingLabel.setText(_translate("Form", "选择标签"))
        self.queryBtn.setText(_translate("Form", "筛选"))
        self.addItemBtn.setText(_translate("Form", "添加到库"))
        self.addRowBtn.setText(_translate("Form", "新增行"))
        self.delRowBtn.setText(_translate("Form", "删除行"))
        self.adviceLabel.setText(_translate("Form", "请选择标签或新增例子"))

    def setTableTitle(self):
        _translate = QtCore.QCoreApplication.translate
        item = self.infoTable.item(0, 0)
        item.setText(_translate("Form", "言葉"))
        item = self.infoTable.item(0, 1)
        item.setText(_translate("Form", "标签"))
        item = self.infoTable.item(0, 2)
        item.setText(_translate("Form", "出处"))
        item = self.infoTable.item(0, 3)
        item.setText(_translate("Form", "中文"))

    def updateEmbCbBox(self, allEmb):
        _translate = QtCore.QCoreApplication.translate
        self.embeddingCbBox.clear()
        for id, emb in enumerate(allEmb):
            self.embeddingCbBox.addItem("")
            self.embeddingCbBox.setItemText(id, _translate("Form", emb))

